In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

In [4]:
from src.config import API_KEY
import requests

In [6]:
url = f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey={API_KEY}"
resposta = requests.get(url)
resposta.json()

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'IBM',
  '3. Last Refreshed': '2026-09-29',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2026-09-29': {'1. open': '220.8650',
   '2. high': '223.1200',
   '3. low': '219.9100',
   '4. close': '219.9900',
   '5. volume': '3633388'},
  '2026-09-28': {'1. open': '222.5000',
   '2. high': '223.1356',
   '3. low': '219.2300',
   '4. close': '220.6700',
   '5. volume': '5291533'},
  '2026-09-25': {'1. open': '226.1500',
   '2. high': '228.9900',
   '3. low': '225.1900',
   '4. close': '225.5100',
   '5. volume': '4147449'},
  '2026-09-24': {'1. open': '232.0000',
   '2. high': '232.6168',
   '3. low': '226.0100',
   '4. close': '227.0600',
   '5. volume': '4149575'},
  '2026-09-23': {'1. open': '233.4700',
   '2. high': '237.8600',
   '3. low': '232.5300',
   '4. close': '232.7600',
   '5. volume': '4539608'},
  '2026-09-22': {'1. open': '234.4700',
   '2. high': '236.2000',
   '3. low': '230.0800',
   '4. close': '231.3800',
   '5. volume': '4808838'},
  '2026-09-21': {'1. open': '231.9900',
   '2. high': '234.7000',
   '3. low': '228.3500',
   '4. close': '231.9300',
   '5. volume': '8200086'},
  '2026-09-18': {'1. open': '237.8500',
   '2. high': '237.8900',
   '3. low': '229.3800',
   '4. close': '229.5500',
   '5. volume': '13413822'},
  '2026-09-17': {'1. open': '238.5800',
   '2. high': '243.3650',
   '3. low': '237.3500',
   '4. close': '237.7500',
   '5. volume': '5905870'},
  '2026-09-16': {'1. open': '240.5000',
   '2. high': '243.3399',
   '3. low': '235.4100',
   '4. close': '237.4900',
   '5. volume': '6181838'},
  '2026-09-15': {'1. open': '246.1900',
   '2. high': '251.8150',
   '3. low': '246.1500',
   '4. close': '248.3700',
   '5. volume': '4518283'},
  '2026-09-14': {'1. open': '249.4100',
   '2. high': '251.3700',
   '3. low': '244.1201',
   '4. close': '249.0900',
   '5. volume': '6817275'},
  '2026-09-11': {'1. open': '235.7800',
   '2. high': '243.6300',
   '3. low': '235.0000',
   '4. close': '243.2900',
   '5. volume': '4919572'},
  '2026-09-10': {'1. open': '238.1800',
   '2. high': '242.3100',
   '3. low': '231.8300',
   '4. close': '234.0200',
   '5. volume': '5820269'},
  '2026-09-09': {'1. open': '232.6500',
   '2. high': '241.5000',
   '3. low': '230.3600',
   '4. close': '239.9400',
   '5. volume': '6404717'},
  '2026-09-08': {'1. open': '232.9500',
   '2. high': '233.4000',
   '3. low': '230.2000',
   '4. close': '232.0900',
   '5. volume': '4787646'},
  '2026-09-04': {'1. open': '233.3300',
   '2. high': '236.1700',
   '3. low': '231.6800',
   '4. close': '234.8900',
   '5. volume': '3722860'},
  '2026-09-03': {'1. open': '234.3800',
   '2. high': '238.2900',
   '3. low': '232.8150',
   '4. close': '234.7100',
   '5. volume': '4375426'},
  '2026-09-02': {'1. open': '230.5450',
   '2. high': '232.8800',
   '3. low': '229.1000',
   '4. close': '231.7000',
   '5. volume': '4654576'},
  '2026-09-01': {'1. open': '231.0000',
   '2. high': '233.0900',
   '3. low': '229.9000',
   '4. close': '231.4000',
   '5. volume': '3240341'},
  '2026-08-31': {'1. open': '232.7300',
   '2. high': '235.9379',
   '3. low': '232.1800',
   '4. close': '233.8700',
   '5. volume': '6101445'},
  '2026-08-28': {'1. open': '238.3000',
   '2. high': '239.0800',
   '3. low': '235.0900',
   '4. close': '235.5900',
   '5. volume': '3945403'},
  '2026-08-27': {'1. open': '232.8000',
   '2. high': '240.8065',
   '3. low': '231.4500',
   '4. close': '238.7900',
   '5. volume': '5505922'},
  '2026-08-26': {'1. open': '230.7000',
   '2. high': '234.2300',
   '3. low': '228.9600',
   '4. close': '229.8700',
   '5. volume': '4631964'},
  '2026-08-25': {'1. open': '230.0000',
   '2. high': '234.4350',
   '3. low': '229.5100',
   '4. close': '234.1900',
   '5. volume': '3023636'},
  '2026-08-24': {'1. open': '234.3700',
   '2. high': '234.4900',
   '3. low': '230.4700',
   '4. close': '231.0400',
   '5. volume': '4085030'},
  '2026-08-21': {'1. open': '233.7100',
   '2. high': '238.7200',
   '3. low': '233.1200',
   '4. close': '235.6800',
   '5. volume': '3888743'},
  '2026-08-20': {'1. open': '236.0000',
   '2. high': '237.5000',
   '3. low': '233.0300',
   '4. close': '233.6900',
   '5. volume': '4986890'},
  '2026-08-19': {'1. open': '232.2600',
   '2. high': '238.6150',
   '3. low': '230.5100',
   '4. close': '237.1600',
   '5. volume': '5342567'},
  '2026-08-18': {'1. open': '229.7300',
   '2. high': '234.4499',
   '3. low': '229.4150',
   '4. close': '232.6700',
   '5. volume': '4650116'},
  '2026-08-17': {'1. open': '231.5900',
   '2. high': '233.6500',
   '3. low': '227.4000',
   '4. close': '228.8500',
   '5. volume': '7564317'},
  '2026-08-14': {'1. open': '238.3700',
   '2. high': '239.1500',
   '3. low': '233.7300',
   '4. close': '234.3200',
   '5. volume': '4523467'},
  '2026-08-13': {'1. open': '238.9200',
   '2. high': '239.7100',
   '3. low': '233.6100',
   '4. close': '237.1400',
   '5. volume': '5395192'},
  '2026-08-12': {'1. open': '236.9500',
   '2. high': '237.4600',
   '3. low': '231.6800',
   '4. close': '235.9800',
   '5. volume': '5696182'},
  '2026-08-11': {'1. open': '236.3100',
   '2. high': '241.8000',
   '3. low': '235.4400',
   '4. close': '238.4200',
   '5. volume': '4468987'},
  '2026-08-10': {'1. open': '235.0000',
   '2. high': '240.7350',
   '3. low': '234.1300',
   '4. close': '236.3100',
   '5. volume': '7348858'},
  '2026-08-07': {'1. open': '235.3800',
   '2. high': '237.3150',
   '3. low': '232.7200',
   '4. close': '237.2800',
   '5. volume': '4763304'},
  '2026-08-06': {'1. open': '229.6100',
   '2. high': '234.4700',
   '3. low': '228.4400',
   '4. close': '233.4300',
   '5. volume': '4250062'},
  '2026-08-05': {'1. open': '236.1000',
   '2. high': '238.9627',
   '3. low': '233.4600',
   '4. close': '235.9200',
   '5. volume': '5726854'},
  '2026-08-04': {'1. open': '224.7600',
   '2. high': '235.3100',
   '3. low': '223.3000',
   '4. close': '235.1500',
   '5. volume': '7537896'},
  '2026-08-03': {'1. open': '228.3300',
   '2. high': '228.5500',
   '3. low': '224.8700',
   '4. close': '226.3100',
   '5. volume': '7974681'},
  '2026-07-31': {'1. open': '221.1500',
   '2. high': '224.7600',
   '3. low': '216.5850',
   '4. close': '223.6500',
   '5. volume': '9093613'},
  '2026-07-30': {'1. open': '222.0000',
   '2. high': '224.8600',
   '3. low': '220.2000',
   '4. close': '221.7400',
   '5. volume': '9675157'},
  '2026-07-29': {'1. open': '227.7000',
   '2. high': '230.9700',
   '3. low': '223.9500',
   '4. close': '226.4400',
   '5. volume': '8806699'},
  '2026-07-28': {'1. open': '219.7300',
   '2. high': '228.9800',
   '3. low': '215.1101',
   '4. close': '227.5500',
   '5. volume': '13262958'},
  '2026-07-27': {'1. open': '217.7500',
   '2. high': '219.6300',
   '3. low': '215.2900',
   '4. close': '216.2800',
   '5. volume': '8369433'},
  '2026-07-24': {'1. open': '209.2800',
   '2. high': '216.1000',
   '3. low': '206.8000',
   '4. close': '214.1900',
   '5. volume': '10578780'},
  '2026-07-23': {'1. open': '202.6400',
   '2. high': '207.5500',
   '3. low': '199.1900',
   '4. close': '206.6500',
   '5. volume': '15306010'},
  '2026-07-22': {'1. open': '207.6800',
   '2. high': '212.3417',
   '3. low': '204.7300',
   '4. close': '205.7700',
   '5. volume': '14606736'},
  '2026-07-21': {'1. open': '210.7200',
   '2. high': '214.9700',
   '3. low': '209.1800',
   '4. close': '210.5000',
   '5. volume': '11954411'},
  '2026-07-20': {'1. open': '210.0700',
   '2. high': '216.2762',
   '3. low': '208.8200',
   '4. close': '213.0000',
   '5. volume': '9585016'},
  '2026-07-17': {'1. open': '215.6200',
   '2. high': '217.1699',
   '3. low': '210.2200',
   '4. close': '212.6700',
   '5. volume': '13150177'},
  '2026-07-16': {'1. open': '208.8200',
   '2. high': '219.9500',
   '3. low': '204.4400',
   '4. close': '219.0500',
   '5. volume': '22533271'},
  '2026-07-15': {'1. open': '220.9650',
   '2. high': '223.8130',
   '3. low': '211.0300',
   '4. close': '211.2000',
   '5. volume': '29590356'},
  '2026-07-14': {'1. open': '226.3650',
   '2. high': '229.9200',
   '3. low': '213.2200',
   '4. close': '217.0700',
   '5. volume': '67440873'},
  '2026-07-13': {'1. open': '290.5000',
   '2. high': '297.5000',
   '3. low': '289.1000',
   '4. close': '290.2300',
   '5. volume': '5024243'},
  '2026-07-10': {'1. open': '297.2600',
   '2. high': '298.7700',
   '3. low': '287.5000',
   '4. close': '287.5600',
   '5. volume': '3640089'},
  '2026-07-09': {'1. open': '285.8350',
   '2. high': '297.2838',
   '3. low': '284.4381',
   '4. close': '295.3000',
   '5. volume': '10841979'},
  '2026-07-08': {'1. open': '300.7700',
   '2. high': '303.8200',
   '3. low': '295.5900',
   '4. close': '302.0500',
   '5. volume': '7416749'},
  '2026-07-07': {'1. open': '305.6600',
   '2. high': '311.8000',
   '3. low': '300.4901',
   '4. close': '306.1300',
   '5. volume': '8618569'},
  '2026-07-06': {'1. open': '288.3450',
   '2. high': '300.8199',
   '3. low': '287.6500',
   '4. close': '299.5200',
   '5. volume': '7181525'},
  '2026-07-02': {'1. open': '283.1400',
   '2. high': '290.9300',
   '3. low': '282.2800',
   '4. close': '289.5200',
   '5. volume': '5950158'},
  '2026-07-01': {'1. open': '279.6600',
   '2. high': '294.4900',
   '3. low': '278.9600',
   '4. close': '286.2500',
   '5. volume': '6905811'},
  '2026-06-30': {'1. open': '273.2100',
   '2. high': '282.5694',
   '3. low': '271.1200',
   '4. close': '281.2100',
   '5. volume': '7458360'},
  '2026-06-29': {'1. open': '274.3000',
   '2. high': '278.1500',
   '3. low': '269.0600',
   '4. close': '278.0000',
   '5. volume': '6464204'},
  '2026-06-26': {'1. open': '258.9400',
   '2. high': '273.1350',
   '3. low': '258.2800',
   '4. close': '271.6300',
   '5. volume': '9719927'},
  '2026-06-25': {'1. open': '267.6700',
   '2. high': '268.7559',
   '3. low': '256.0000',
   '4. close': '258.2700',
   '5. volume': '8539694'},
  '2026-06-24': {'1. open': '261.8430',
   '2. high': '265.0700',
   '3. low': '256.1836',
   '4. close': '262.9600',
   '5. volume': '8149935'},
  '2026-06-23': {'1. open': '261.5800',
   '2. high': '267.5300',
   '3. low': '255.2600',
   '4. close': '264.9400',
   '5. volume': '15686117'},
  '2026-06-22': {'1. open': '248.4300',
   '2. high': '253.3100',
   '3. low': '243.8100',
   '4. close': '252.2200',
   '5. volume': '9615393'},
  '2026-06-18': {'1. open': '251.3800',
   '2. high': '252.4700',
   '3. low': '243.6800',
   '4. close': '249.1000',
   '5. volume': '16619749'},
  '2026-06-17': {'1. open': '266.3500',
   '2. high': '268.8700',
   '3. low': '261.8800',
   '4. close': '262.3500',
   '5. volume': '5537042'},
  '2026-06-16': {'1. open': '270.8700',
   '2. high': '276.6200',
   '3. low': '268.6100',
   '4. close': '270.8100',
   '5. volume': '4917642'},
  '2026-06-15': {'1. open': '272.0000',
   '2. high': '272.2500',
   '3. low': '264.8000',
   '4. close': '268.7100',
   '5. volume': '7178779'},
  '2026-06-12': {'1. open': '278.9400',
   '2. high': '278.9400',
   '3. low': '267.6800',
   '4. close': '272.2400',
   '5. volume': '5748915'},
  '2026-06-11': {'1. open': '268.0000',
   '2. high': '276.4799',
   '3. low': '266.5000',
   '4. close': '274.8500',
   '5. volume': '7558322'},
  '2026-06-10': {'1. open': '273.8200',
   '2. high': '280.5100',
   '3. low': '271.3300',
   '4. close': '272.3600',
   '5. volume': '5497137'},
  '2026-06-09': {'1. open': '281.1350',
   '2. high': '283.5900',
   '3. low': '271.2900',
   '4. close': '277.4900',
   '5. volume': '9007918'},
  '2026-06-08': {'1. open': '286.4400',
   '2. high': '290.5000',
   '3. low': '279.4300',
   '4. close': '280.8200',
   '5. volume': '6790639'},
  '2026-06-05': {'1. open': '300.0000',
   '2. high': '302.3000',
   '3. low': '281.0701',
   '4. close': '284.8400',
   '5. volume': '12509480'},
  '2026-06-04': {'1. open': '307.4250',
   '2. high': '310.4400',
   '3. low': '300.1800',
   '4. close': '301.7700',
   '5. volume': '9608097'},
  '2026-06-03': {'1. open': '318.2950',
   '2. high': '318.2950',
   '3. low': '302.5301',
   '4. close': '305.6300',
   '5. volume': '13926558'},
  '2026-06-02': {'1. open': '313.7500',
   '2. high': '332.4600',
   '3. low': '310.1090',
   '4. close': '329.2300',
   '5. volume': '17210696'},
  '2026-06-01': {'1. open': '322.5500',
   '2. high': '327.9800',
   '3. low': '308.0000',
   '4. close': '320.4200',
   '5. volume': '32880180'},
  '2026-05-29': {'1. open': '277.3000',
   '2. high': '300.9999',
   '3. low': '273.3300',
   '4. close': '297.8000',
   '5. volume': '28480996'},
  '2026-05-28': {'1. open': '261.0000',
   '2. high': '268.8900',
   '3. low': '257.0000',
   '4. close': '264.2200',
   '5. volume': '12432879'},
  '2026-05-27': {'1. open': '250.4550',
   '2. high': '257.6200',
   '3. low': '250.4550',
   '4. close': '255.2000',
   '5. volume': '9275543'},
  '2026-05-26': {'1. open': '254.5500',
   '2. high': '254.5500',
   '3. low': '245.4500',
   '4. close': '250.6900',
   '5. volume': '9256109'},
  '2026-05-22': {'1. open': '262.0500',
   '2. high': '264.3800',
   '3. low': '253.3900',
   '4. close': '253.8400',
   '5. volume': '19072873'},
  '2026-05-21': {'1. open': '232.5800',
   '2. high': '253.6300',
   '3. low': '230.9350',
   '4. close': '252.9700',
   '5. volume': '25707791'},
  '2026-05-20': {'1. open': '221.0500',
   '2. high': '225.0000',
   '3. low': '216.7800',
   '4. close': '225.0000',
   '5. volume': '4858990'},
  '2026-05-19': {'1. open': '224.5000',
   '2. high': '227.3500',
   '3. low': '221.9200',
   '4. close': '222.3300',
   '5. volume': '5937754'},
  '2026-05-18': {'1. open': '218.5500',
   '2. high': '223.3300',
   '3. low': '217.7500',
   '4. close': '222.7500',
   '5. volume': '5946367'},
  '2026-05-15': {'1. open': '218.2000',
   '2. high': '220.9100',
   '3. low': '217.6150',
   '4. close': '219.3000',
   '5. volume': '6154450'},
  '2026-05-14': {'1. open': '215.5450',
   '2. high': '220.9600',
   '3. low': '215.0000',
   '4. close': '218.3700',
   '5. volume': '5906199'},
  '2026-05-13': {'1. open': '218.2700',
   '2. high': '218.3100',
   '3. low': '212.3400',
   '4. close': '214.6400',
   '5. volume': '8361214'},
  '2026-05-12': {'1. open': '224.4300',
   '2. high': '224.4300',
   '3. low': '219.2200',
   '4. close': '219.2200',
   '5. volume': '6045225'},
  '2026-05-11': {'1. open': '228.6600',
   '2. high': '230.2300',
   '3. low': '222.5500',
   '4. close': '223.5500',
   '5. volume': '6677186'},
  '2026-05-08': {'1. open': '229.7300',
   '2. high': '230.7050',
   '3. low': '224.8300',
   '4. close': '229.7600',
   '5. volume': '5332800'},
  '2026-05-07': {'1. open': '227.5000',
   '2. high': '231.8200',
   '3. low': '227.4100',
   '4. close': '231.3100',
   '5. volume': '5485545'}}}

In [8]:
dados = resposta.json()
dados.keys()

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [13]:
import pandas as pd

In [14]:
serie = dados["Time Series (Daily)"]
df = pd.DataFrame.from_dict(serie, orient ="index")
df.head()

             1. open   2. high    3. low  4. close 5. volume
2026-09-29  220.8650  223.1200  219.9100  219.9900   3633388
2026-09-28  222.5000  223.1356  219.2300  220.6700   5291533
2026-09-25  226.1500  228.9900  225.1900  225.5100   4147449
2026-09-24  232.0000  232.6168  226.0100  227.0600   4149575
2026-09-23  233.4700  237.8600  232.5300  232.7600   4539608

In [15]:
df = df.rename(columns = {
    "1. open": "abertura",
    "2. high": "maxima",
    "3. low": "minima",
    "4. close": "fechamento",
    "5. volume": "volume"
})

In [17]:
df.head(5)

            abertura    maxima    minima fechamento   volume
2026-09-29  220.8650  223.1200  219.9100   219.9900  3633388
2026-09-28  222.5000  223.1356  219.2300   220.6700  5291533
2026-09-25  226.1500  228.9900  225.1900   225.5100  4147449
2026-09-24  232.0000  232.6168  226.0100   227.0600  4149575
2026-09-23  233.4700  237.8600  232.5300   232.7600  4539608

In [20]:
df.shape

(100, 5)

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, 2026-09-29 to 2026-05-07
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   abertura    100 non-null    str
 1   maxima      100 non-null    str
 2   minima      100 non-null    str
 3   fechamento  100 non-null    str
 4   volume      100 non-null    str
dtypes: str(5)
memory usage: 8.8+ KB

In [23]:
df.isna().sum()

abertura      0
maxima        0
minima        0
fechamento    0
volume        0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [28]:
df = df.astype({
    "abertura": float,
    "maxima": float,
    "minima": float,
    "fechamento": float,
    "volume": int
})

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, 2026-09-29 to 2026-05-07
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   abertura    100 non-null    float64
 1   maxima      100 non-null    float64
 2   minima      100 non-null    float64
 3   fechamento  100 non-null    float64
 4   volume      100 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 8.8+ KB

In [31]:
df.index.dtype

In [32]:
df.index = pd.to_datetime(df.index)
df.index.dtype

dtype('<M8[us]')

In [36]:
import json 

with open("../data/raw/ibm_daily_raw.json", "w") as arquivo:
    json.dump(dados, arquivo)

In [37]:
df.to_csv("../data/processed/ibm_daily.csv")